### PR TITLE
Stable and main debian repository

### PR DESCRIPTION
**Pull request by elaur**
I think this repo is much correct.

### CODE REVIEW

**Comment by Notos** [comment]
Stable will soon be Wheezy, not Squeeze anymore and then this script might break for everyone. Have you tested it on Wheezy? I did a try and it not went good. Script is not really using those repos, they are there just for some people that are not on OVH to have a good list of sources at hand, but, still, it can cause some trouble.

**Comment by elaur** [comment]
Wheezy is under testing version  4, for now Squeeze is stable, i tested this repo under my VPS and is fine.

**Comment by Notos** [comment]
Yeah, but what I mean is that when you point to a stable repository, as soon as a new distro is launched (it become stable), this repository will point to it. So if we point to stable now, as soon as Wheezy is launched, this repo will also move to Wheezy and some boxes can break while installing or updating packages.

**Comment by elaur** [comment]
oh yes, just replace "stable" from first two line with "squeeze", anyway wheezy i think will not be lunched this year.

**Comment by Notos** [comment]
Just made sources compliant with http://wiki.debian.org/SourcesList.

Thanks!

**Pull request closed without merging**
